GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Fred",
    "age": 65
}

###

GET http://localhost:3000/api/users/624c3029508e9e703ecf4564

###

PUT http://localhost:3000/api/users/624d917f31523ad9131e8c22
Content-Type: application/json

{
    "name": "Albert",
    "age": 76
}

###

DELETE http://localhost:3000/api/users/6254152f76fa45dedeae7e3b